apiVersion: v1
stringData:
  permissions: $PGO_PERMS
  rolename: $PGO_ROLENAME
kind: Secret
metadata:
  labels:
    pgo-created-by: upgrade
    pgo-pgorole: "true"
    rolename: $PGO_ROLENAME
    vendor: radondb
  name: pgorole-$PGO_ROLENAME
  namespace: $PGO_OPERATOR_NAMESPACE
type: Opaque

