resources:
- ../../base
namePrefix: dev-
namespace: pgo
commonLabels:
  environment: development

patchesJson6902:
  - target:
      group: radondb.com
      version: v1
      namespace: pgo
      kind: Pgcluster
      name: dev-hippo
    path: devhippo.json
  - target:
      group: radondb.com
      version: v1
      namespace: pgo
      kind: Pgcluster
      name: dev-hippo
    path: bouncer.json