resources:
- ../../base
namePrefix: prod-
namespace: pgo
commonLabels:
  environment: production

patchesJson6902:
  - target:
      group: radondb.com
      version: v1
      namespace: pgo
      kind: Pgcluster
      name: prod-hippo
    path: prodhippo.json